package com.urbanairship.statshtable;

public enum OpType {
    GET, MULTIGET, GET_ROW_OR_BEFORE, PUT, BATCH, GET_SCANNER, NEXT, EXISTS, CHECK_AND_PUT, DELETE, 
    INCREMENT, CHECK_AND_DELETE, MULTIPUT, MULTIDELETE, FLUSHCOMMITS, LOCKROW, UNLOCKROW, 
    RESULTSCANNER_ITERATOR, RESULTSCANNER_NEXT, RESULTSCANNER_NEXTARRAY, RESULTSCANNER_CLOSE, 
    RESULTITERATOR_HASNEXT, RESULTITERATOR_NEXT, GETSCANNER
}